[WIP] txt diagnosis tool
AstraZeneca-Omics/immport-galaxy-tools pull request #94
Opened 2020-07-14 14:34 UTC by emily101-gif

2020-07-15 09:33 UTC, emily101-gif commented
@pcm32 . Would you mind having a look at the python script for this tool. The tool works, and does produces a summary of the input.txt file (without errors). However the file with errors (NAN / character strings) does not show any warnings when running.

2020-07-15 11:36 UTC, pcm32 commented
This now passes the test, hopefully detecting what you were after @emily101-gif. Is the python code the original one from Immport? I would guess that there are more sophisticated ways of checking for NaNs in a pandas table that having to iterate on rows and columns, could you give that a quick look @emily101-gif?

2020-07-15 11:41 UTC, pcm32 commented
I would rather see something like this: https://stackoverflow.com/questions/14016247/find-integer-index-of-rows-with-nan-in-pandas-dataframe

2020-07-15 11:54 UTC, pcm32 requested changes
Well done! A few things to improve this PR, thanks!

2020-07-15 11:54 UTC, pcm32 commented on flowtools/txt_diagnosis/txtdiagnosis.py
> +            if df[cols].count() != len(df[cols]):
Please give it a go at using the pandas dataframe more natively here for finding out in a couple of lines the offending lines with NaNs, and then reporting that in the same way.

2020-07-16 11:26 UTC, pcm32 approved these changes
We will leave this for now in the interest of time

2020-07-16 11:26 UTC, merged